command: ['npm', 'run', 'start']
env:
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres
  - name: DATABRICKS_ENDPOINT
    value: 'databricks-gpt-5-4-mini'
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie-space
